apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask-scheduler
  namespace: psmops-dask-production
  labels:
    app: dask-scheduler
    environment: production
    context: dask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-scheduler
  template:
    metadata:
      labels:
        app: dask-scheduler
    spec:
      containers:
        - name: dask-scheduler
          image: daskdev/dask
          args:
            - dask-scheduler
          ports:
            - containerPort: 8786
            - containerPort: 8787
---
apiVersion: v1
kind: Service
metadata:
  name: dask-scheduler
  namespace: psmops-dask-production
  labels:
    environment: production
    context: dask
spec:
  type: LoadBalancer
  selector:
    app: dask-scheduler
  ports:
    - port: 8786
      targetPort: 8786
      name: dask-scheduler-loadbalancer
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dask-dashboard
  namespace: psmops-dask-production
  labels:
    environment: production
    context: dask
spec:
  type: LoadBalancer
  selector:
    app: dask-scheduler
  ports:
    - port: 8787
      targetPort: 8787
      name: dask-dashboard-loadbalancer
      protocol: TCP

